openapi: 3.0.0
info:
  title: ValoVision API
  description: API documentation for ValoVision Backend
  version: "1.0"
servers:
  - url: http://localhost:8000/api
paths:
  /agents:
    get:
      summary: List all agents
      operationId: getAgents
      tags:
        - Agents
      responses:
        '200':
          description: A list of agents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Agent'
        '404':
          description: No agents added yet.
        '500':
          description: Error fetching agents
    post:
      summary: Create a new agent
      operationId: createAgent
      tags:
        - Agents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Agent'
      responses:
        '201':
          description: Agent created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  agentID:
                    type: integer
                    format: int64
        '500':
          description: Error creating agent
  /agents/{id}:
    get:
      summary: Get a single agent by ID
      operationId: getAgentById
      tags:
        - Agents
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Agent found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agent'
        '404':
          description: Agent not found
        '500':
          description: Error fetching agent by ID
components:
  schemas:
    Agent:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        agentPortraitLink:
          type: string
          format: uri
